[package]
name = "steam_market_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.8"
actix-web = "4.11.0"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
tera = "1.20.1"
tokio = { version = "1.48.0", features = ["full"] }
